name: Tests

on:
  pull_request:
  push:

jobs:
  phpunit:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
      - name: Install PHPUnit
        run: |
          wget -O phpunit https://phar.phpunit.de/phpunit-10.phar
          chmod +x phpunit
      - name: Run tests
        run: ./phpunit --configuration phpunit.xml
